package tests

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/smart-libs/go-crosscutting/transaction/spec/lib/pkg (interfaces: EventNotifier)
//
// Generated by this command:
//    mockgen -destination=./event_notifier_mock.go -package=tests github.com/smart-libs/go-crosscutting/transaction/spec/lib/pkg EventNotifier
// Package tests is a generated GoMock package.

import (
	"github.com/smart-libs/go-crosscutting/event/spec/lib/pkg"
	"github.com/smart-libs/go-crosscutting/transaction/spec/lib/pkg"
	"go.uber.org/mock/gomock"
	"reflect"
)

// MockEventNotifier is a mock of EventNotifier interface.
type MockEventNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockEventNotifierMockRecorder
}

// MockEventNotifierMockRecorder is the mock recorder for MockEventNotifier.
type MockEventNotifierMockRecorder struct {
	mock *MockEventNotifier
}

// NewMockEventNotifier creates a new mock instance.
func NewMockEventNotifier(ctrl *gomock.Controller) *MockEventNotifier {
	mock := &MockEventNotifier{ctrl: ctrl}
	mock.recorder = &MockEventNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventNotifier) EXPECT() *MockEventNotifierMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEventNotifier) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEventNotifierMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEventNotifier)(nil).Close))
}

// Notify mocks base method.
func (m *MockEventNotifier) Notify(arg0 transaction.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Notify", arg0)
}

// Notify indicates an expected call of Notify.
func (mr *MockEventNotifierMockRecorder) Notify(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockEventNotifier)(nil).Notify), arg0)
}

// Register mocks base method.
func (m *MockEventNotifier) Register(arg0 event.Listener[transaction.Event]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", arg0)
}

// Register indicates an expected call of Register.
func (mr *MockEventNotifierMockRecorder) Register(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockEventNotifier)(nil).Register), arg0)
}

// Unregister mocks base method.
func (m *MockEventNotifier) Unregister(arg0 event.Listener[transaction.Event]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unregister", arg0)
}

// Unregister indicates an expected call of Unregister.
func (mr *MockEventNotifierMockRecorder) Unregister(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unregister", reflect.TypeOf((*MockEventNotifier)(nil).Unregister), arg0)
}
