// Code generated by MockGen. DO NOT EDIT.
// Source: transaction (interfaces: EventNotifierFactory)
//
// Generated by this command:
//
//	mockgen -destination=./event_notifier_factory_mock.go -package=tests transaction EventNotifierFactory
//
// Package tests is a generated GoMock package.
package tests

import (
	event "github.com/smart-libs/go-crosscutting/event/spec/lib/pkg"
	"github.com/smart-libs/go-crosscutting/transaction/spec/lib/pkg"
	gomock "go.uber.org/mock/gomock"
	reflect "reflect"
)

// MockEventNotifierFactory is a mock of EventNotifierFactory interface.
type MockEventNotifierFactory struct {
	ctrl     *gomock.Controller
	recorder *MockEventNotifierFactoryMockRecorder
}

// MockEventNotifierFactoryMockRecorder is the mock recorder for MockEventNotifierFactory.
type MockEventNotifierFactoryMockRecorder struct {
	mock *MockEventNotifierFactory
}

// NewMockEventNotifierFactory creates a new mock instance.
func NewMockEventNotifierFactory(ctrl *gomock.Controller) *MockEventNotifierFactory {
	mock := &MockEventNotifierFactory{ctrl: ctrl}
	mock.recorder = &MockEventNotifierFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventNotifierFactory) EXPECT() *MockEventNotifierFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEventNotifierFactory) Create(arg0 ...event.NotifierFactoryOptions) event.Notifier[transaction.Event] {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(event.Notifier[transaction.Event])
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEventNotifierFactoryMockRecorder) Create(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEventNotifierFactory)(nil).Create), arg0...)
}
